# Generated by Django 5.0.4 on 2024-05-12 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_ordermodel_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='email',
        ),
    ]
